spring:
  profiles:
    active:
    - dev
---                             # -三个减号位分隔符  实现了同一个文件不同的配置
spring:
  profiles: dev			# -开发环境
  application:
    name: microservicecloud-config-ps-dev
---
spring:
  profiles: test		# -测试环境
  application:
    name: microservicecloud-config-ps-test

# -请务必保存为UTF-8格式