spring:
  profiles:
    active:
    - dev
---                             # -三个减号位分隔符  实现了同一个文件不同的配置

server:
  port: 8001                    # -注册中心占用7001端口，冒号后面必须要有空格
spring:
  profiles: dev
  application:
    name: microservicecloud-config-dept-client
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: org.gjt.mm.mysql.Driver
      url: jdbc:mysql://localhost:3306/cloudDB01
      username: root
      password: zy1600988812
      dbcp2:
        min-idle: 5
        initial-size: 5
	max-total: 5
        max-wait-millss:200

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.ps.springcloud.entities
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: dept-8001.com
    prefer-id-address: true

info:
  app.name: ps-microservicecloud-springcloudconfig01
  company.name: www.ps.cpm
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---                             # -三个减号位分隔符  实现了同一个文件不同的配置

server:
  port: 8001
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml      # mybatis配置文件所在路径
  type-aliases-package: com.ps.springcloud.entities       # 所有entity别名类所在包
  mapper-locations:
  -  classpath:mybatis/mapper/**/*.xml                    # mapper映射文件

spring:
  application:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource          # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver            # mysql驱动包
    url: jdbc:mysql://localhost:3306/clouddb02?characterEncoding=UTF-8            # 数据库名称
    username: root
    password: zy1600988812
    dbcp2:
      min-idle: 5                                         # 数据库连接池的最小维持连接数
      initial-size: 5                                     # 初始化连接数
      max-total: 5                                        # 最大连接数
      max-wait-millis: 200                                # 等待连接获取的最大超时时间
      
eureka:
  client:                                                 # 客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: microservicecloud-dept8001               # 给当前入住进去的eureka实例做别名处理（自定义服务）
    prefer-ip-address: true                               # 访问路径可以显示IP地址
    
info:
  app.name: ps-microservicecloud
  company.name: www.ps.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

# -请务必保存为UTF-8格式